spring.application.name=api-gateway
server.port=8887

eureka.client.service-url.defaultZone=http://localhost:8888/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=governance-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://GOVERNANCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/policies/**

spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**

## routing config for audit service
#spring.cloud.gateway.server.webmvc.routes[2].id=audit-service
#spring.cloud.gateway.server.webmvc.routes[2].uri=lb://AUDIT-SERVICE
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/audit/**