spring.application.name=audit-service
spring.datasource.url=jdbc:postgresql://localhost:5433/audit_service_db
spring.datasource.username=postgres
spring.datasource.password=pass12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true