spring.application.name=user-service
server.port=8877

spring.datasource.url=jdbc:postgresql://localhost:5433/user_service_db
spring.datasource.username=postgres
spring.datasource.password=pass12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8888/eureka/